package co.edu.unicauca.mycompany.projects.presentation;

import co.edu.unicauca.mycompany.projects.access.Factory;
import co.edu.unicauca.mycompany.projects.access.ICompanyRepository;
import co.edu.unicauca.mycompany.projects.domain.entities.Company;
import co.edu.unicauca.mycompany.projects.domain.entities.Coordinator;
import co.edu.unicauca.mycompany.projects.domain.entities.Project;
import co.edu.unicauca.mycompany.projects.domain.services.CompanyService;
import co.edu.unicauca.mycompany.projects.domain.services.EmailService;
import co.edu.unicauca.mycompany.projects.domain.services.ProjectService;
import co.edu.unicauca.mycompany.projects.infra.Messages;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Interfaz gráfica para gestionar comentarios dentro de un proyecto.
 * Permite a un coordinador interactuar con los comentarios asociados a un proyecto.
 */
public class GUIComentarios extends javax.swing.JFrame {

    /**
     * Proyecto asociado a los comentarios.
     */
    private Project proyecto;

    /**
     * Coordinador que interactúa con la interfaz de comentarios.
     */
    private final Coordinator coordinator;

    /**
     * Servicio para gestionar operaciones relacionadas con los proyectos.
     */
    private final ProjectService projectService;

    /**
     * Servicio para gestionar operaciones relacionadas con las empresas.
     */
    private final CompanyService companyService;
    
    /**
     * Constructor de la interfaz gráfica de comentarios.
     * Inicializa los servicios y configura la ventana.
     *
     * @param projectService Servicio para la gestión de proyectos.
     * @param proyecto Proyecto al que pertenecen los comentarios.
     * @param coordinator Coordinador que interactúa con la interfaz.
     * @param companyService Servicio para la gestión de empresas.
     */
    public GUIComentarios(ProjectService projectService, Project proyecto, Coordinator coordinator, CompanyService companyService) {
        this.proyecto = proyecto;
        this.coordinator = coordinator;
        this.projectService = projectService;
        ICompanyRepository companyRepository = Factory.getInstance().getRepositoryCompany("MARIADB"); 
        this.companyService = new CompanyService(companyRepository); // Se inicializa correctamente
        
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false); 
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // Agregar un placeholder al campo de texto
        TextPrompt placeholderUsername = new TextPrompt("Ingresar un comentario: ",textFielCorreo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        textFielCorreo = new javax.swing.JTextField();
        btnEnviarComentario = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(38, 42, 65));
        jLabel11.setText("Comentario");

        jLabel29.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(84, 84, 84));
        jLabel29.setText("Escribe un comentario para la empresa");

        textFielCorreo.setBackground(new java.awt.Color(227, 230, 235));
        textFielCorreo.setForeground(new java.awt.Color(130, 134, 140));
        textFielCorreo.setBorder(null);
        textFielCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFielCorreoActionPerformed(evt);
            }
        });

        btnEnviarComentario.setBackground(new java.awt.Color(90, 111, 228));
        btnEnviarComentario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnviarComentario.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarComentario.setText("Enviar");
        btnEnviarComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarComentarioActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(95, 97, 112));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel11)
                    .addComponent(textFielCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnEnviarComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(textFielCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnEnviarComentario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFielCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFielCorreoActionPerformed
        
    }//GEN-LAST:event_textFielCorreoActionPerformed

    /**
     * Maneja el evento cuando el usuario presiona el botón "Enviar Comentario".
     * Captura el comentario ingresado, valida su contenido, obtiene la empresa asociada 
     * al proyecto y envía un correo electrónico con el comentario al contacto de la empresa.
     * 
     * @param evt Evento de acción generado al presionar el botón.
     */
    private void btnEnviarComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarComentarioActionPerformed
        String comentario = textFielCorreo.getText().trim(); // Captura el texto del campo de entrada

        if (comentario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El comentario no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtener la empresa asociada al proyecto
        Company empresa = companyService.getCompany(proyecto.getIdcompany());

        if (empresa == null || empresa.getUserEmail() == null || empresa.getUserEmail().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontró la empresa asociada al proyecto o su correo no está definido.", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Definir destinatario y cuerpo del correo
        String destinatarioEmpresa = empresa.getUserEmail();
        String asunto = "Nuevo Comentario del Proyecto: " + proyecto.getProTitle();
        String cuerpo = "Coordinador: " + coordinator.getUserId()+ "\n"
                      + "Proyecto: " + proyecto.getProTitle()+ "\n"
                      + "Comentario:\n" + comentario;

        // Enviar el correo
        EmailService.sendEmail(destinatarioEmpresa, asunto, cuerpo);

        // Limpiar el campo de texto y cerrar la ventana
        textFielCorreo.setText("");
        this.dispose();

         // Mostrar mensaje de confirmación
        Messages.mensajeVario("Comentario enviado correctamente.");
    }//GEN-LAST:event_btnEnviarComentarioActionPerformed

    /**
     * Maneja el evento cuando el usuario presiona el botón "Cerrar".
     * Cierra la ventana actual sin realizar ninguna otra acción.
     * 
     * @param evt Evento de acción generado al presionar el botón.
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarComentario;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textFielCorreo;
    // End of variables declaration//GEN-END:variables
}
