package co.edu.unicauca.mycompany.projects.presentation;

import co.edu.unicauca.mycompany.projects.domain.entities.Student;
import co.edu.unicauca.mycompany.projects.domain.services.CompanyService;
import co.edu.unicauca.mycompany.projects.domain.services.ProjectService;
import javax.swing.JButton;

/**
 * Clase que representa la interfaz gráfica donde un estudiante puede ver los proyectos disponibles.
 * Permite visualizar y postularse a proyectos en los que el estudiante esté interesado.
 */
public class GUIProyectosDisponibles extends javax.swing.JFrame {

    /** Estudiante que está visualizando los proyectos disponibles. */
    private final Student student;

    /** Botón en la pantalla principal que permite postularse rápidamente. */
    private final JButton btnPostularInicio;

    /**
     * Constructor de la clase GUIProyectosDisponibles.Inicializa la interfaz con la información del estudiante y los proyectos disponibles.
     *
     * @param student          Estudiante que está visualizando los proyectos.
     * @param projectService   Servicio encargado de gestionar los proyectos y sus postulaciones.
     * @param companyService   Servicio encargado de gestionar las empresas de los proyectos.
     * @param btnPostularInicio Botón de la pantalla principal para postulación rápida.
     */
    public GUIProyectosDisponibles(Student student, ProjectService projectService, CompanyService companyService, JButton btnPostularInicio) {
        this.student = student;
        this.btnPostularInicio = btnPostularInicio;

        // Inicializar los componentes gráficos de la interfaz
        initComponents();

        // Configurar la apariencia y datos visuales
        initVisual();

        // Agregar un observador para actualizar la tabla de proyectos disponibles
        projectService.addObserver(new TableProjectsStudentObserver(student, projectService, companyService, jTableEstudiante, jScrollPane1));
    }

    /**
     * Configura la apariencia inicial de la ventana.
     * Hace visible la interfaz, la centra en la pantalla y deshabilita el redimensionamiento.
     * También establece la información del estudiante en los elementos gráficos.
     */
    public final void initVisual() {
        this.setVisible(true); 
        setResizable(false); 
        setLocationRelativeTo(null); 
        btnInicio.setText("Estudiante " + student.getUserId());
        lblCorreo.setText(student.getUserEmail());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnMisProyectos = new javax.swing.JButton();
        lblCorreo = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnPostular1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstudiante = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jPanel4.setBackground(new java.awt.Color(90, 111, 228));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMisProyectos.setBackground(new java.awt.Color(90, 111, 228));
        btnMisProyectos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnMisProyectos.setForeground(new java.awt.Color(186, 195, 241));
        btnMisProyectos.setText("Mis proyectos");
        btnMisProyectos.setBorder(null);
        btnMisProyectos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMisProyectos.setFocusPainted(false);
        btnMisProyectos.setFocusable(false);
        btnMisProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisProyectosActionPerformed(evt);
            }
        });
        jPanel4.add(btnMisProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 210, 50));

        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorreo.setText("tuEstudiante@gmail.com");
        jPanel4.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 190, -1));

        btnInicio.setBackground(new java.awt.Color(90, 111, 228));
        btnInicio.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Estudiante X");
        btnInicio.setBorder(null);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setFocusPainted(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel4.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 210, 50));

        btnPostular1.setBackground(new java.awt.Color(90, 111, 228));
        btnPostular1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnPostular1.setForeground(new java.awt.Color(255, 255, 255));
        btnPostular1.setText("Postularme");
        btnPostular1.setBorder(null);
        btnPostular1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPostular1.setFocusPainted(false);
        btnPostular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostular1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnPostular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(38, 42, 65));
        jLabel10.setText("Postularme en proyectos");

        jTableEstudiante.setForeground(new java.awt.Color(38, 42, 65));
        jTableEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nombre Empresa", "Nombre Proyecto", "Fecha", "Resumen", "Acciones"
            }
        ));
        jTableEstudiante.setGridColor(new java.awt.Color(204, 204, 204));
        jTableEstudiante.setRowHeight(45);
        jTableEstudiante.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTableEstudiante);
        jTableEstudiante.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMisProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisProyectosActionPerformed
        
    }//GEN-LAST:event_btnMisProyectosActionPerformed

    /**
    * Maneja el evento de acción cuando se presiona el botón "Inicio".
    * Cierra la ventana actual y vuelve a hacer visible el botón de postulación en la pantalla principal.
    *
    * @param evt Evento de acción generado por el botón.
    */
    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        dispose();
        btnPostularInicio.setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnPostular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostular1ActionPerformed
       
    }//GEN-LAST:event_btnPostular1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMisProyectos;
    private javax.swing.JButton btnPostular1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstudiante;
    private javax.swing.JLabel lblCorreo;
    // End of variables declaration//GEN-END:variables
}
