package co.edu.unicauca.mycompany.projects.presentation;

import co.edu.unicauca.mycompany.projects.domain.entities.Coordinator;
import co.edu.unicauca.mycompany.projects.domain.entities.Project;
import co.edu.unicauca.mycompany.projects.domain.services.CompanyService;
import co.edu.unicauca.mycompany.projects.domain.services.ProjectService;

/**
 * Clase que representa un panel de acciones para que un coordinador interactúe con un proyecto.
 * Permite visualizar detalles del proyecto, cambiar su estado y agregar comentarios.
 */
public class PanelActionCoordinator extends javax.swing.JPanel {
    
    /** Proyecto sobre el cual se realizarán acciones. */
    private Project proyecto;
    
    /** Coordinador que interactúa con el panel. */
    private final Coordinator coordinator;
    
    /** Servicio de gestión de proyectos. */
    private final ProjectService projectService;
    
    /** Servicio de gestión de empresas. */
    private final CompanyService companyService;

    /**
     * Constructor de la clase PanelActionCoordinator.
     * 
     * @param projectService Servicio de gestión de proyectos.
     * @param proyecto Proyecto sobre el cual se realizarán acciones.
     * @param coordinator Coordinador que interactúa con el proyecto.
     * @param companyService Servicio de gestión de empresas.
     */
    public PanelActionCoordinator(ProjectService projectService, Project proyecto, Coordinator coordinator, CompanyService companyService) {
        this.proyecto = proyecto;
        this.coordinator = coordinator;
        this.projectService = projectService;
        this.companyService = companyService;

        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDetalles = new javax.swing.JButton();
        btnEstado = new javax.swing.JButton();
        btnComentario = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnDetalles.setBackground(new java.awt.Color(41, 64, 211));
        btnDetalles.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDetalles.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles.setText("Detalles");
        btnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesActionPerformed(evt);
            }
        });

        btnEstado.setBackground(new java.awt.Color(22, 192, 152));
        btnEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEstado.setForeground(new java.awt.Color(255, 255, 255));
        btnEstado.setText("Estado");
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });

        btnComentario.setBackground(new java.awt.Color(230, 11, 11));
        btnComentario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnComentario.setForeground(new java.awt.Color(255, 255, 255));
        btnComentario.setText("Comentario");
        btnComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComentario)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalles)
                    .addComponent(btnEstado)
                    .addComponent(btnComentario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método invocado al presionar el botón de detalles.
     * Abre una ventana con la información detallada del proyecto.
     * 
     * @param evt Evento de acción generado por el botón.
     */
    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed
        GUIVerDetalles detallesFrame = new GUIVerDetalles(proyecto);
       detallesFrame.setVisible(true);
    }//GEN-LAST:event_btnDetallesActionPerformed

    /**
     * Método invocado al presionar el botón de estado.
     * Permite modificar el estado del proyecto.
     * 
     * @param evt Evento de acción generado por el botón.
     */
    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        GUIEstado estadoFrame = new GUIEstado(projectService, proyecto, coordinator, companyService);
        estadoFrame.setVisible(true);
    }//GEN-LAST:event_btnEstadoActionPerformed

    /**
     * Método invocado al presionar el botón de comentarios.
     * Abre una ventana para agregar comentarios al proyecto.
     * 
     * @param evt Evento de acción generado por el botón.
     */
    private void btnComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentarioActionPerformed
        GUIComentarios comentariosFrame = new GUIComentarios(projectService, proyecto, coordinator, companyService);
        comentariosFrame.setVisible(true);
    }//GEN-LAST:event_btnComentarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComentario;
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnEstado;
    // End of variables declaration//GEN-END:variables
}
