server:
  port: 8086

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      #default-filters:
      #  - TokenRelay
      routes:
        - id: microservice-company
          uri: http://company-microservice:8085  # Changed from localhost
          predicates:
            - Path=/company/**
          filters:
            - StripPrefix=1
        - id: microservice-coordinator
          uri: http://coordinator-microservice:8081  # Changed from localhost
          predicates:
            - Path=/coordinator/**
          filters:
            - StripPrefix=1
        - id: microservice-student
          uri: http://student-microservice:8083  # Changed from localhost
          predicates:
            - Path=/student/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/sistema  # Changed from localhost

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG