server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: microservice-company
          uri: http://localhost:8085
          predicates:
            - Path=/company/**
          filters:
            - StripPrefix=1
        - id: microservice-b
          uri: http://localhost:8083
          predicates:
            - Path=/b/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sistema

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
